#!/usr/bin/env bash
# Regenerate .env.paper from GCP Secret Manager. Run at bootstrap and after ANY
# secret rotation (then: sudo systemctl restart sharpe-eod sharpe-dashboard).
#
# On a GCE VM, gcloud authenticates automatically via the attached service account
# (metadata server) — no interactive login needed, as long as that SA has the
# roles/secretmanager.secretAccessor role.
#
# Only true secrets live in Secret Manager. DATABASE_URL uses local peer auth over
# the Unix socket (no credentials), so it is written here directly.
set -euo pipefail

APP_DIR="${APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PROJECT="${GCP_PROJECT:-$(gcloud config get-value project 2>/dev/null || true)}"
# On a GCE VM the project is always available from the metadata server.
[ -z "$PROJECT" ] && PROJECT="$(curl -s -H 'Metadata-Flavor: Google' \
  http://metadata.google.internal/computeMetadata/v1/project/project-id || true)"
: "${PROJECT:?could not determine GCP project (set GCP_PROJECT)}"
ENV_FILE="$APP_DIR/.env.paper"

get() { gcloud secrets versions access latest --secret="$1" --project="$PROJECT"; }

umask 177  # files created mode 600
cat > "$ENV_FILE" <<EOF
# Generated by deploy/fetch_secrets.sh from Secret Manager (project: $PROJECT). Do not commit.
ALPACA_API_KEY=$(get alpaca-api-key)
ALPACA_SECRET_KEY=$(get alpaca-secret-key)
ALPACA_BASE_URL=https://paper-api.alpaca.markets
ALPACA_DATA_URL=https://data.alpaca.markets
DATABASE_URL=postgresql:///sharpe_engine
SMTP_PASSWORD=$(get smtp-password)
# Optional — the Caddy basic-auth password, included in alert emails as the dashboard login.
# Absent secret ⇒ empty ⇒ emails just omit the password. Set it with:
#   printf %s '<caddy password>' | gcloud secrets create dashboard-password --data-file=- --replication-policy=automatic
DASHBOARD_PASSWORD=$(get dashboard-password 2>/dev/null || true)
EOF
chmod 600 "$ENV_FILE"
echo "wrote $ENV_FILE (mode 600) from Secret Manager [project=$PROJECT]"
